FROM node:20-alpine

WORKDIR /app

# Instalar Angular CLI global (opcional si ya está en devDependencies)
RUN npm install -g @angular/cli

# Copiar dependencias
COPY package*.json ./
RUN npm install

# El resto del código se monta como volumen (no se copia)

EXPOSE 4200

CMD ["ng", "serve", "--host", "0.0.0.0", "--poll", "2000"]